### ISSUE TITLE
Cannot load library icui18n (v2)

### ISSUE THREAD

**Issue by arthurkirkosa** [NitMedia/wkhtml2pdf#46]
I'm getting this issue
```bash
/var/www/app/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 --lowquality --print-media-type --header-right '[page]/[toPage]' '/tmp/knp_snappy544e5ffa54d496.58211283.html' '/tmp/knp_snappy544e5ffa54d496.58211283.pdf'
Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolInvalidOperationError
```

**Comment by chonthu** [comment]
apt-get install libicu48

**Comment by arthurkirkosa** [comment]
ubuntu 14.04

```sh
sudo apt-get install libicu48
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libicu48 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu48' has no installation candidate
```

**Comment by chonthu** [comment]
You’ll have to search for the missing package with aptitude search libicu*


Best

-- 






Nithin Meppurathu

**Comment by arthurkirkosa** [comment]
I already have ```libicu52``` installed, but wkhtml2pdf keeps asking for 48

**Comment by chonthu** [comment]
The version you installed might be "too new". Its probably looking for specific paths. This issue should be filled with the main wkhtmltopdf package, as this my package is just a pdf wrapper for that library. My suggestion would be to downgrade or try the dev packages.

**Comment by arthurkirkosa** [comment]
yes, it's specific to wkhtmltopdf package and not the wrapper's issue. thought that there might be others who encountered the same issue and might have a fix

48 won't install in ubuntu 14.04 as it's available up to v12 :(

**Comment by chonthu** [comment]
Install it from source

**Comment by arthurkirkosa** [comment]
well, that might be just too much for my skills :)

**Comment by chonthu** [comment]
I wonder if the new package for wkhtmltopdf fixed this issue, i could try upgrading my source version for you. You can do it manually and let me know if it works and ill update my wrapper.


Best

-- 






Nithin Meppurathu

**Comment by arthurkirkosa** [comment]
I'm using
```
$ vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 -V
wkhtmltopdf 0.12.2.1 (with patched qt)
```
Is there a newer package?

**Comment by chonthu** [comment]
Nope thats the latest, sorry i was thinking you where using the one that i have with my wrapper.


Best

-- 






Nithin Meppurathu

**Comment by arthurkirkosa** [comment]
I've opened an issue https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2245 
We'll see what answers we get.

**Comment by janzenz** [comment]
@arthurkirkosa May I know how did you solve this?

**Comment by ghost** [comment]
@chonthu @arthurkirkosa Did you find a fix for this? I can't get it working at all on Ubuntu 14.04.02, and I use this with a Laravel event ticketing management system called [Attendize](https://github.com/Attendize/Attendize) 

Attendize throws this when it should redirect to a new page after the PDF ticket is generated. It is in fact generated, and the ticket order registers in the database, but I still get the error, which breaks the redirect. It is always either throwing up the icui18 error for all of three of executables in the vendor folder (as in Attendize FAQ), or the message below if I run an Ubuntu executable from .env downloaded from Wkhtml2pdf website:

Exception in Wkhtml2pdf.php line 885:
System error /home/vagrant/Code/eventum/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb: 2: /home/vagrant/Code/eventum/vendor/nitmedia/wkhtml2pdf/src/Nitmedia/Wkhtml2pdf/lib/wkhtmltox-0.13.0-alpha-7b36694_linux-trusty-amd64.deb: Syntax error: newline unexpected

I've tried multiple things to fix this.

- First I had libxext and libxrender errors. Fixed it with apt-get libxext6 and apt-get libxrender1
- Downloaded executable as mentioned above and updated .env
- apt-get update, apt-get install wkhtmltopdf, apt-get install libicu48 (did not exist). [This](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2242#issuecomment-82343649) recommended to install libicu52, I ran apt-get install libicu52 and it installed successfully.
- Followed [this](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2242#issuecomment-82343649) topic thoroughly, and the end of it seems to talk about image tags. Do you have any ideas which tags they might be referring to?

Pulled all my hair out here, but maybe you know a magic fix!

Sorry if I missed something, I'm learning and this is a little bit beyond my scope of understanding.

The temp solution (but its far from an ideal one) was to comment Lines 871 to 890 in Wkhtml2pdf.php file and returning $input instead of $data.
